#!/usr/bin/env python3
#==============================================================================
# Copyright (c) 2026 KritvaOS
# SPDX-License-Identifier: Apache-2.0
#
# File        : check_api_surface.py
# Description : Detects changes to the public API surface of the installed headers against a reviewed snapshot.
#
# Component   : Kritva Core
# Module      : Audit
# Layer       : Core Foundation
#
# Requirements: CORE-COMPAT-009
# API         : CORE-API-SURFACE-SNAPSHOT
#
# Author      : KritvaOS Core Team
# Created     : 05-10-2026
#==============================================================================
"""Compare the public declaration surface of include/kritva/core/ with tests/compat/api_surface.snapshot.

The surface of a header is the ordered list of its public and protected declarations (namespace and class scope, enum
bodies, attributes, signatures, qualifiers, default member initializers and base lists). Comments, preprocessor lines,
function bodies and private members are not part of the surface. A difference is reported as a *candidate* so that a
deliberate breaking change cannot be mistaken for an accidental regression:
  - a removed or changed declaration, a reordering, or a removed header: an Incompatible candidate;
  - an added declaration: a Review-required candidate;
  - a new header: a Compatible candidate (it also needs an inventory row).
Every candidate fails the audit until the change passes the evolution review of docs/compatibility/VERSIONING_POLICY.md and
the snapshot is regenerated deliberately with --update (the regenerated snapshot is part of the reviewed change).
Standard library only; deterministic. `--self-test` proves each kind of change is detected and that comment, function-body
and private-member edits are not reported.
"""
import argparse
import os
import re
import shutil
import sys
import tempfile

SNAPSHOT = os.path.join("tests", "compat", "api_surface.snapshot")
BANNER = ("# Kritva Core public API surface snapshot (CORE-COMPAT-009).\n"
          "# Generated by scripts/audit/check_api_surface.py --update from include/kritva/core/.\n"
          "# A change to this file is a public API change: it needs a recorded evolution review\n"
          "# (docs/compatibility/VERSIONING_POLICY.md). Do not edit by hand.\n")


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def strip(text):
    """Remove comments, preprocessor lines and the contents of string and character literals."""
    out, i, n = [], 0, len(text)
    while i < n:
        c = text[i]
        if text.startswith("//", i):
            j = text.find("\n", i)
            i = n if j < 0 else j
        elif text.startswith("/*", i):
            j = text.find("*/", i + 2)
            i = n if j < 0 else j + 2
            out.append(" ")
        elif c in "\"'":
            j = i + 1
            while j < n and text[j] != c:
                j += 2 if text[j] == "\\" else 1
            out.append(c + c)
            i = j + 1
        else:
            out.append(c)
            i += 1
    text = "".join(out)
    return re.sub(r"^[ \t]*#.*$", "", text, flags=re.M)


def norm(text):
    text = " ".join(text.split())
    text = re.sub(r"\s+([,;)\]>])", r"\1", text)
    return re.sub(r"([(\[<])\s+", r"\1", text)


def skip_group(text, i):
    """text[i] is an opening bracket; return the index after its matching close."""
    pairs = {"{": "}", "(": ")", "[": "]"}
    stack = [pairs[text[i]]]
    i += 1
    while i < len(text) and stack:
        c = text[i]
        if c in pairs:
            stack.append(pairs[c])
        elif c == stack[-1]:
            stack.pop()
        i += 1
    return i


ACCESS = re.compile(r"^\s*(public|private|protected)\s*:\s*")


def scan(text, i, scope, access, out, header):
    """Walk one block; append (scope, declaration) pairs for public/protected declarations."""
    n = len(text)
    while i < n:
        j = i
        depth = 0
        while j < n:                         # the head ends at ; { or } outside parentheses/brackets
            c = text[j]
            if c in "([":
                depth += 1
            elif c in ")]":
                depth -= 1
            elif depth == 0 and c in ";{}":
                break
            j += 1
        head = text[i:j]
        while True:                          # leading access specifiers change the access, they are not declarations
            m = ACCESS.match(head)
            if not m:
                break
            access = m.group(1)
            head = head[m.end():]
        term = text[j] if j < n else ""
        h = norm(head)
        if term == "}":
            if h:
                out.append((scope, h)) if access != "private" else None
            return j + 1
        if not term:
            return n
        if term == ";":
            if h and not h.startswith("friend") and access != "private":
                out.append((scope, h))
            i = j + 1
            continue
        # term == "{"
        m = re.match(r"^(?:template\s*<.*>\s*)?(class|struct|union)\s+(?:\[\[[^\]]*\]\]\s*)?(\w+)", h)
        if h.startswith("namespace"):
            name = h.split()[1] if len(h.split()) > 1 else ""
            i = scan(text, j + 1, scope + [name] if name else scope, "public", out, header)
        elif m and "(" not in h.split(m.group(2), 1)[0]:
            if access != "private":
                out.append((scope, h))
            i = scan(text, j + 1, scope + [m.group(2)], "public" if m.group(1) != "class" else "private", out, header)
            while i < n and text[i] in " \t\r\n":
                i += 1
            if i < n and text[i] == ";":
                i += 1
        elif h.startswith(("enum", "template") and "enum") or re.match(r"^enum\b", h):
            end = skip_group(text, j)
            if access != "private":
                out.append((scope, h + " " + norm(text[j:end])))
            i = end
            while i < n and text[i] in " \t\r\n":
                i += 1
            if i < n and text[i] == ";":
                i += 1
        elif "(" in h:                         # a function definition: record the signature, skip the body
            k = j
            if re.search(r"\)[^()]*:\s*\w", h) and not re.search(r"\)\s*(const|noexcept|override|final|&|&&|\s)*$", h):
                pass                           # constructor with a member-initializer list; handled below
            ctor = re.search(r"\)\s*(?:noexcept(?:\([^)]*\))?\s*)?:(?!:)", h)
            if ctor:
                h = norm(h[:ctor.start() + 1] + h[ctor.start() + 1:ctor.end() - 1])
                prev = ""
                while k < n:                   # skip initializers until the body brace
                    if text[k] == "{":
                        stripped = text[j:k].rstrip()
                        if not stripped or stripped[-1] in ")}" and prev != "init":
                            break
                        k = skip_group(text, k)
                        continue
                    if text[k] == "(":
                        k = skip_group(text, k)
                        continue
                    k += 1
                j = k
            if access != "private":
                out.append((scope, h))
            i = skip_group(text, j)
        else:                                  # a variable or member with a brace initializer
            end = skip_group(text, j)
            if access != "private":
                out.append((scope, h + " " + norm(text[j:end])))
            i = end
            while i < n and text[i] in " \t\r\n;":
                i += 1
            continue
    return i


def surface(root):
    base = os.path.join(root, "include", "kritva", "core")
    result = {}
    for d, _, files in os.walk(base):
        for name in sorted(files):
            if name.endswith(".hpp"):
                rel = os.path.relpath(os.path.join(d, name), base).replace(os.sep, "/")
                out = []
                scan(strip(read(os.path.join(d, name))), 0, [], "public", out, rel)
                result[rel] = ["::".join(s) + " :: " + decl for s, decl in out]
    return result


def render(surf):
    lines = [BANNER]
    for header in sorted(surf):
        lines.append(f"@@ {header}\n")
        lines.extend(f"{decl}\n" for decl in surf[header])
    return "".join(lines)


def load(path):
    surf, cur = {}, None
    for line in read(path).splitlines():
        if line.startswith("#") or not line.strip():
            continue
        if line.startswith("@@ "):
            cur = line[3:].strip()
            surf[cur] = []
        elif cur is not None:
            surf[cur].append(line)
    return surf


def compare(root):
    errors = []
    snap = os.path.join(root, SNAPSHOT)
    if not os.path.isfile(snap):
        return [f"{SNAPSHOT.replace(os.sep, '/')} is missing (generate it with --update)"]
    old, new = load(snap), surface(root)
    for header in sorted(set(old) | set(new)):
        if header not in new:
            errors.append(f"{header}: header removed -> Incompatible candidate (needs evolution review and a MAJOR release)")
            continue
        if header not in old:
            errors.append(f"{header}: new header -> Compatible candidate (needs an inventory row, documentation and a regenerated snapshot)")
            continue
        o, n = old[header], new[header]
        if o == n:
            continue
        removed = [x for x in o if x not in n]
        added = [x for x in n if x not in o]
        for x in removed:
            errors.append(f"{header}: declaration removed or changed -> Incompatible candidate: {x}")
        for x in added:
            errors.append(f"{header}: declaration added -> Review-required candidate: {x}")
        if not removed and not added:
            errors.append(f"{header}: declarations reordered -> Incompatible candidate (order is part of the surface)")
    return errors


def _edit(tmp, rel, old, new):
    path = os.path.join(tmp, "include", "kritva", "core", rel)
    text = read(path)
    if old not in text:
        raise SystemExit(f"self-test setup error: {old!r} not found in {rel}")
    with open(path, "w", encoding="utf-8") as f:
        f.write(text.replace(old, new, 1))


def self_test(root):
    cap, err, lif = "capability/capability_set.hpp", "error/error_code.hpp", "lifecycle/lifecycle_state.hpp"
    comp = "runtime/component.hpp"
    positives = [
        ("an added public member function", lambda t: _edit(t, cap, "    [[nodiscard]] bool contains(", "    [[nodiscard]] int extra() const noexcept;\n    [[nodiscard]] bool contains("), "Review-required candidate"),
        ("a changed signature", lambda t: _edit(t, cap, "const Capability* find(CapabilityId", "Capability* find(CapabilityId"), "Incompatible candidate"),
        ("a removed noexcept", lambda t: _edit(t, cap, "bool contains(CapabilityId id) const noexcept", "bool contains(CapabilityId id) const"), "Incompatible candidate"),
        ("an added enumerator", lambda t: _edit(t, err, "INTERNAL_ERROR", "INTERNAL_ERROR, EXTRA"), "Review-required candidate"),
        ("a changed enumerator value", lambda t: _edit(t, "types/timestamp.hpp", "REALTIME = 1", "REALTIME = 2"), "Incompatible candidate"),
        ("a reordered enumeration", lambda t: _edit(t, lif, "READY,\n       RUNNING,", "RUNNING,\n       READY,"), "Incompatible candidate"),
        ("an added virtual member", lambda t: _edit(t, comp, "class Component {\npublic:", "class Component {\npublic:\n    virtual void extra() = 0;"), "Review-required candidate"),
        ("a removed header", lambda t: os.remove(os.path.join(t, "include", "kritva", "core", "types", "version.hpp")), "header removed"),
        ("a new header", lambda t: open(os.path.join(t, "include", "kritva", "core", "types", "extra.hpp"), "w").write("namespace kritva::core { struct Extra { int x{}; }; }\n"), "new header"),
        ("a removed snapshot", lambda t: os.remove(os.path.join(t, SNAPSHOT)), "is missing"),
    ]
    negatives = [
        ("a comment-only edit", lambda t: _edit(t, cap, "#pragma once", "#pragma once\n// a new comment /* nested */ with `quotes` and 'q'\n/* block\n comment */")),
        ("a function-body-only edit", lambda t: _edit(t, "statistics/counter.hpp", "{ value_ += amount; }", "{ value_ += amount + 0; }")),
        ("a private-member addition", lambda t: _edit(t, cap, "private:", "private:\n    int hidden_for_selftest_{0};")),
        ("whitespace reflow", lambda t: _edit(t, err, "NONE = 0,", "NONE   =   0 ,")),
    ]
    failures = 0

    def prepare(mutate):
        tmp = tempfile.mkdtemp(prefix="apisurf_selftest_")
        shutil.copytree(os.path.join(root, "include"), os.path.join(tmp, "include"))
        os.makedirs(os.path.join(tmp, "tests", "compat"))
        shutil.copy(os.path.join(root, SNAPSHOT), os.path.join(tmp, SNAPSHOT))
        mutate(tmp)
        return tmp

    for label, mutate, expected in positives:
        tmp = prepare(mutate)
        try:
            if not any(expected in e for e in compare(tmp)):
                print(f"[api-surface] SELF-TEST FAILED: the audit did not detect {label}")
                failures += 1
        finally:
            shutil.rmtree(tmp, ignore_errors=True)
    for label, mutate in negatives:
        tmp = prepare(mutate)
        try:
            errs = compare(tmp)
            if errs:
                print(f"[api-surface] SELF-TEST FAILED: {label} must not be reported, got: {errs[0]}")
                failures += 1
        except SystemExit as e:
            print(f"[api-surface] SELF-TEST FAILED: {e}")
            failures += 1
        finally:
            shutil.rmtree(tmp, ignore_errors=True)
    if compare(root):
        print("[api-surface] SELF-TEST FAILED: the real surface differs from the snapshot")
        failures += 1
    if failures == 0:
        print(f"[api-surface] self-test passed: {len(positives)} changes detected, {len(negatives)} non-changes ignored")
    return failures


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
    parser.add_argument("--update", action="store_true", help="regenerate the snapshot (a deliberate, reviewed act)")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    root = os.path.abspath(args.root)
    if args.self_test:
        return 1 if self_test(root) else 0
    if args.update:
        os.makedirs(os.path.join(root, "tests", "compat"), exist_ok=True)
        with open(os.path.join(root, SNAPSHOT), "w", encoding="utf-8") as f:
            f.write(render(surface(root)))
        print(f"[api-surface] snapshot regenerated: {sum(len(v) for v in surface(root).values())} declarations")
        return 0
    errors = compare(root)
    for e in errors:
        print(f"[api-surface] ERROR: {e}")
    surf = surface(root)
    print(f"[api-surface] {len(surf)} headers, {sum(len(v) for v in surf.values())} declarations, {len(errors)} difference(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
